markdown: redcarpet
name: Unit testing in Node.js
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Setup
  url: setup/
  internal: true
  children:
  - text: Adding the tools to your own project
    url: tools/
    internal: true
- text: Designing the application
  url: designing-the-application/
  internal: true
- text: Designing the core logic module
  url: core-logic/
  internal: true
- text: Concepts
  url: concepts/
  internal: true
  children:
  - text: Code reuse
    url: code-reuse/
    internal: true
  - text: Dependency injection
    url: dependency-injection/
    internal: true
  - text: Exploration, vision, and settlement
    url: exploration-vision-and-settlement/
    internal: true
  - text: Seams
    url: seams/
    internal: true
  - text: Testability
    url: testability/
    internal: true
- text: Further reading
  url: further-reading/
  internal: true

repos:
- name: Unit testing in Node.js
  description: Main repository
  url: https://github.com/18F/unit-testing-node

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

google_analytics_ua: UA-48605964-19

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"
